version: '3.7'

services:
  server:
    container_name: server
    image: aidamgly/server_ataquebeastfinal

    ports:
      - "8443:8443"
    networks:
      tfgnet:
        ipv4_address: 172.23.0.2
    tty: true

  attack:
    container_name: attack
    image: aidamgly/attack_beast
    networks:
      tfgnet:
        ipv4_address: 172.23.0.3
    volumes:
      - /home/beast/attack:/home
    tty: true


networks:
  tfgnet:
#    attachable: true
    ipam:
      config:
        - subnet: 172.23.0.0/16
